### PR TITLE
Update groupId to "io.ebean"

### PR DESCRIPTION
**Pull request by sorra**
I see in maven central the groupId changed from org.avaje.ebean to io.ebean

### CODE REVIEW

**Comment by rbygrave** [comment]
Thanks for this.  Note that this repo is generated from the source at: https://github.com/ebean-orm/website-source

... so really these changes need to be made there.  If you want to do that let me know ... otherwise I can make the same changes there.

Thanks, Rob.

**Comment by sorra** [comment]
Did it. Please review that one.

**Comment by rbygrave** [comment]
I don't see any pull requests for https://github.com/ebean-orm/website-source ?

**Comment by sorra** [comment]
Sorry, I missed the final step creating the PR.
Did it again.

**Comment by rbygrave** [comment]
closing (merged into website-source)

**Pull request closed without merging**
