### PR TITLE
Upgrade API documentation

### PR DESCRIPTION
**Pull request by thibaultmeyer**
Following changes has been done:

  - API documentation for Ebean 9 has been added
  - API documentation for Ebean 10 has been added
  - Normalize API documentation path (/apidoc/_EBEAN-VERSION_)
  - Change all HREF links to use the new API documentation path

### CODE REVIEW

**Comment by rbygrave** [comment]
Changes to the website need to go into: https://github.com/ebean-orm/website-source ... and from there the website is generated. Hmmm.

**Comment by thibaultmeyer** [comment]
Don't see any folder "apidocs", is auto generated ? Is it more a generator related issue ? or any script to generate website.

Would be possible to backport theses modifications to have hoster javadoc up to date on Ebean website ?

**Comment by rbygrave** [comment]
Yes.  the apidoc is just the generated javadoc.  I've just updated and pushed the version 10 javadoc.

**Comment by rbygrave** [comment]
Closing this.  Javadoc was updated etc.

**Pull request closed without merging**
